compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.1.cjs
