name: build_deploy

on:
  push:
    branches:
    - master
    # - staging
  pull_request:
  repository_dispatch:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - uses: actions/checkout@v4

      - name: Enable Yarn Berry
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      # - name: Compile all packages
      #   # TODO: Get rid of, the esbuild step should be sufficient.
      #   # However, currently some packages rely on `compiled/` paths,
      #   # which are created by running `compile` commands.
      #   run: |
      #     yarn compile-all

  # Deployment job
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Trigger deployment of convert.glossarist.org
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_deploy.yml
          repo: glossarist/convert.glossarist.org
          # inputs: '{ "message": "blah blah", "something": false }'
