name: trigger_webgui_deploy

on:
  push:
    branches:
    - master
    # - staging
  pull_request:
  repository_dispatch:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # Deployment job
  trigger_webgui_deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment of convert.paneron.org
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_deploy.yml
          repo: paneron/convert.paneron.org
          token: ${{ secrets.GLOSSARIST_CI_PAT_TOKEN }}
          ref: main
          # inputs: '{ "message": "blah blah", "something": false }'
