name: compile_all

on:
  push:
    branches:
    - master
  pull_request:
  repository_dispatch:
  workflow_dispatch:

jobs:
  compile_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Enable Yarn Berry
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Compile all packages
        run: |
          yarn compile-all

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: webgui-dist
          path: packages/webgui/dist/
