name: deploy-master

on:
  schedule:
    - cron: '42 */12 * * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - uses: actions/checkout@master
      - name: Enable Yarn Berry
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      # - name: Compile all packages
      #   # TODO: Get rid of, the esbuild step should be sufficient.
      #   # However, currently some packages rely on `compiled/` paths,
      #   # which are created by running `compile` commands.
      #   run: |
      #     yarn compile-all
      - name: Build site
        run: |
          yarn workspace webgui build --debug

      - name: Upload built site artifact
        uses: actions/upload-artifact@v3
        with:
          name: webgui-dist
          path: packages/webgui/dist

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws configure set default.s3.max_concurrent_requests 100
          aws configure set default.s3.max_queue_size 10000
          aws configure set default.s3.use_accelerate_endpoint true
          aws configure set default.s3.payload_signing_enabled false
          aws s3 sync packages/webgui/dist s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.html" --content-type "text/html; charset=utf-8"
          aws s3 sync packages/webgui/dist s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.json" --content-type "application/json; charset=utf-8"
          aws s3 sync packages/webgui/dist s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.jsonld" --content-type "application/ld+json; charset=utf-8"
          aws s3 sync packages/webgui/dist s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.ttl" --content-type "text/turtle; charset=utf-8"
          aws s3 sync packages/webgui/dist s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --include "*" --exclude "*.html" --exclude "*.json" --exclude "*.jsonld" --exclude "*.ttl"
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
